services:
  # The main PUZI service that will read and validate an UZI user
  puzi_auth.service:
    class: MinVWS\PUZI\AuthBundle\Security\PUZIService
    arguments: [
      "@puzi_auth.uzi.reader",
      "@puzi_auth.uzi.validator"
    ]

  # Main reader class
  puzi_auth.uzi.reader:
    class: MinVWS\PUZI\UziReader

  # Main validator class
  puzi_auth.uzi.validator:
    class: MinVWS\PUZI\UziValidator
    arguments: [
      "%puzi_auth.strict_ca_check%",
      "%puzi_auth.allowed_types%",
      "%puzi_auth.allowed_roles%"
    ]

  # Actual guard service that can be used inside your security.yml
  puzi_auth.security.guard.authenticator:
    class: MinVWS\PUZI\AuthBundle\Security\Guard\GuardAuthenticator
    arguments: [
      "@puzi_auth.service"
    ]
